[package]
name = "mnist-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
flate2 = "1.0.34"
rand = "0.8.5"
serde = { version = "1.0", default-features = false, features = ["derive"] }
serde_json = "1"

[profile.release]
opt-level = 3
strip = true
lto = true
